name: main

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build the docker-compose stack
        run: docker-compose up --build -d
      - name: Check running containers
        run: docker-compose ps
      - name: Check mongodb connection step1
        run: docker-compose exec mongodb mongo
      - name: Check mongodb connection step2
        run: db.getMongo()
      - name: Check mongodb connection step3
        run: exit
      - name: test
        run: go test -race -v ./...
