name: main

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build the docker-compose stack
        run: docker-compose up -d mongodb
      - name: Check running containers
        run: docker-compose ps
      - name: wait for mongodb UP
        run: sleep 5
      #- name: run build.go
      #  run: go build .
      #- name: run main.go
      #  run: go run main.go &
      - name: test
        run: go test -race -v ./...
      #- name: docker build
      #  run: docker build -t kenobata/golang-scraping  .
      #- name: dockerhub push
      #  run: docker push kenobata/golang-scraping:latest